import localFont from "next/font/local";
import "./globals.css";
import "./fonts.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-[100svh] w-[100svw]">
      <body className="h-full w-full">{children}</body>
    </html>
  );
}
